version: '3.1'
services:
  mongo:
    image: mongo:latest
    #  restart: always
    ports: 
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: genai
      MONGO_INITDB_ROOT_PASSWORD: genaipass
    volumes:
     - $HOME/MyMongoGenAIDb:/data/db
    container_name: mongoGenAiDB
